### ISSUE TITLE
display <type> e.g not done or done

### ISSUE THREAD

**Issue by Denniskzq** [cs2103jan2016-W13-1J/main#65]

**Comment by thbl2012** [comment]
Valid patterns for [type]:
1. "all" : all tasks
2. "float", "undecided", "floating": float tasks
3. "deadline", "normal": deadlines
4. "session", "event": sessions
5. "repeating", "routine", "recurring", "repeat", "recur": recurring tasks
6. <date string> eg. "04/04/2016", "next tuesday", "tmr": tasks on that day
7. "done", "completed", "finished": done tasks
8. "undone", "uncompleted", "unfinished", "pending": undone tasks
9. "past": tasks whose dates have passed
10. list of valid patterns: [type1] [type2]... [type3]....
